// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PollBuilder.Voting.Data;

#nullable disable

namespace PollBuilder.Voting.Data.Migrations
{
    [DbContext(typeof(VotingDbContext))]
    [Migration("20260818091924_InitialVotes")]
    partial class InitialVotes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("voting")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PollBuilder.Voting.Models.Vote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OptionIndex")
                        .HasColumnType("integer");

                    b.Property<string>("PollCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("VotedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VoterToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("PollCode", "OptionIndex");

                    b.HasIndex("PollCode", "VoterToken")
                        .IsUnique();

                    b.ToTable("Votes", "voting");
                });
#pragma warning restore 612, 618
        }
    }
}
